export const typography = {
  hero: "text-5xl lg:text-7xl font-extrabold leading-tight font-sans",
  pageTitle: "text-2xl lg:text-4xl font-bold font-sans",
  sectionTitle: "text-2xl lg:text-3xl font-bold font-sans",
  subsectionTitle: "text-xl lg:text-2xl font-semibold font-sans",
  cardTitle: "text-lg lg:text-xl font-semibold font-sans",
  cardSubtitle: "text-base lg:text-lg font-semibold font-sans",
  body: "text-base lg:text-lg leading-8 font-sans",
  article: "text-lg lg:text-xl leading-8 font-sans",
  bodySecondary: "text-base lg:text-lg leading-7 font-sans",
  navigation: "text-base lg:text-lg font-medium font-sans",
  navigationMobile: "text-lg font-medium font-sans",
  footerTitle: "text-base font-semibold font-sans",
  footerLink: "text-base font-sans",
  copyright: "text-sm font-sans",
  formLabel: "text-base font-medium font-sans",
  formInput: "text-base font-sans",
  formHelper: "text-sm font-sans",
  errorText: "text-sm font-medium font-sans",
  timestamp: "text-[11px] font-mono uppercase tracking-widest",
  metadata: "text-xs font-mono uppercase tracking-widest",
  microLabel: "text-[11px] font-mono uppercase tracking-widest",
  projectName: "text-xl lg:text-2xl font-bold font-sans",
  projectCategory: "text-base font-sans",
  projectDescription: "text-base lg:text-lg leading-7 font-sans",
  techTag: "text-sm font-medium font-mono",
  processTitle: "text-lg lg:text-xl font-semibold font-sans",
  journalTitle: "text-xl lg:text-2xl font-bold font-sans",
  journalDate: "text-sm font-mono",
  journalBody: "text-base lg:text-lg leading-8 font-sans",
  aiChat: "text-base lg:text-lg leading-7 font-sans",
  aiResponse: "text-base lg:text-lg leading-8 font-sans",
  aiInput: "text-base font-sans",
  dashboardTitle: "text-2xl lg:text-3xl font-bold font-sans",
  dashboardWidgetTitle: "text-lg lg:text-xl font-semibold font-sans",
  dashboardMetric: "text-3xl lg:text-4xl font-bold font-sans",
  dashboardTable: "text-base lg:text-lg font-sans",
  sidebarItem: "text-base lg:text-lg font-medium font-sans",
  sidebarLabel: "text-xs font-mono uppercase tracking-widest",
} as const;

export type TypographyKey = keyof typeof typography;