export const typography = {
  hero: "text-5xl lg:text-7xl font-bold leading-tight",
  pageTitle: "text-3xl lg:text-4xl font-bold",
  sectionTitle: "text-3xl font-bold",
  subsectionTitle: "text-2xl font-semibold",
  cardTitle: "text-xl font-semibold",
  cardSubtitle: "text-lg font-semibold",
  body: "text-base lg:text-lg leading-7",
  article: "text-lg lg:text-xl leading-8",
  bodySecondary: "text-base leading-7",
  navigation: "text-base font-medium",
  navigationMobile: "text-lg font-medium",
  footerTitle: "text-base font-semibold",
  footerLink: "text-base",
  copyright: "text-sm",
  formLabel: "text-base font-medium",
  formInput: "text-base",
  formHelper: "text-sm",
  errorText: "text-sm font-medium",
  timestamp: "text-xs font-mono",
  metadata: "text-xs font-mono uppercase tracking-widest",
  microLabel: "text-[11px] font-mono font-bold uppercase tracking-widest",
  projectName: "text-2xl font-bold",
  projectCategory: "text-base",
  projectDescription: "text-base leading-7",
  techTag: "text-sm font-medium",
  processTitle: "text-xl font-semibold",
  journalTitle: "text-2xl font-bold",
  journalDate: "text-sm",
  journalBody: "text-base lg:text-lg leading-8",
  aiChat: "text-base leading-7",
  aiResponse: "text-base lg:text-lg leading-8",
  aiInput: "text-base",
  dashboardTitle: "text-3xl font-bold",
  dashboardWidgetTitle: "text-lg font-semibold",
  dashboardMetric: "text-4xl font-bold",
  dashboardTable: "text-base",
  sidebarItem: "text-base font-medium",
  sidebarLabel: "text-xs font-mono uppercase tracking-widest",
} as const;

export type TypographyKey = keyof typeof typography;